export default {
	multipass: true,
	plugins: [
		{
			name: 'preset-default',
			params: {
				overrides: {
					removeViewBox: false,
					removeMetadata: true,
					convertPathData: {
						straightCurves: false,
						floatPrecision: 5,
					},
				},
			},
		},
		{
			name: 'cleanupNumericValues',
			params: {
				floatPrecision: 5,
			},
		},
		{
			name: 'inlineStyles',
			params: {
				onlyMatchedOnce: false,
			},
		},
		'removeDoctype',
		'removeXMLProcInst',
		'removeComments',
		'removeMetadata',
		'removeEditorsNSData',
		'cleanupAttrs',
		'mergeStyles',
		'inlineStyles',
		'minifyStyles',
		'convertStyleToAttrs',
		'cleanupIds',
		'removeRasterImages',
		'removeUselessDefs',
		'cleanupNumericValues',
		'cleanupListOfValues',
		'convertColors',
		'removeNonInheritableGroupAttrs',
		'removeUselessStrokeAndFill',
		'cleanupEnableBackground',
		'removeHiddenElems',
		'removeUnknownsAndDefaults',
		'removeEmptyText',
		'moveElemsAttrsToGroup',
		'moveGroupAttrsToElems',
		'collapseGroups',
		'convertPathData',
		'convertEllipseToCircle',
		'convertTransform',
		'removeEmptyAttrs',
		'removeEmptyContainers',
		'mergePaths',
		'removeUnusedNS',
		'reusePaths',
		'sortAttrs',
		'sortDefsChildren',
		'removeTitle',
		'removeDesc',
		'removeDimensions',
		'removeStyleElement',
		'removeScriptElement',
	],
};
